Snapshot of latest.

diff --git a/pcontracts/src/examples/Makefile b/pcontracts/src/examples/Makefile
--- a/pcontracts/src/examples/Makefile
+++ b/pcontracts/src/examples/Makefile
@@ -1,10 +1,18 @@
-RT_DIR=../runtime
-RES_DIR=../../results
-BASE_RES_DIR=$(RES_DIR)/base
-BASE_ORACLE_DIR=../data
+ROOT_DIR=../..
 
-CHECK_STATUS=../../.checkStatus
-#CHECK_STATUS_ALL=../../.checkStatus*
+include $(ROOT_DIR)/make.inc
+
+SRC_DIR=..
+
+RES_DIR=$(ROOT_DIR)/results
+RT_DIR=$(SRC_DIR)/runtime
+
+BASE_RES_DIR=$(RES_DIR)/base
+BASE_ORACLE_DIR=$(SRC_DIR)/data
+
+CHECK_ALL_STATUS=$(ROOT_DIR)/$(CHECK_STATUS)
+CHECK_SRC_STATUS=$(SRC_DIR)/$(CHECK_STATUS)
+
 RI_DIR=RoutineInstrumenter
 VI_DIR=VisitInstrumenter
 INSTR_DIRS=$(RI_DIR) $(VI_DIR)
@@ -66,68 +74,59 @@ BINARIES=$(KS_BINARIES) $(ROSE_BINARIES)
 all: $(BINARIES)
 
 check: checkClean all checkSetup checkKnapsackTests checkRose
-	@echo; \
-	if [ -f $(CHECK_STATUS) ]; then \
-	  res=`cat $(CHECK_STATUS)`; \
-	  if [ "$$res" -eq "0" ]; then \
-	    echo; echo "Complete Test Suite:  FAILED";\
-	    echo; echo "Review output to identify failure(s)"; \
-	  else \
-	    echo; echo "Complete Test Suite:  PASSED";\
-	  fi; \
-	  rm -f $(CHECK_STATUS); \
-	else \
-	  echo; echo "*******"; \
-	  echo "WARNING:  $(CHECK_STATUS) is missing.  Cannot assess suite."; \
-	  echo "*******"; \
-	fi; \
+	@$(MAKE) checkSummary; \
 	echo "DONE (check)"; echo
 
 checkAll: checkClean all checkSetup checkKnapsackTests checkRose checkContracts
-	@echo; \
-	if [ -f $(CHECK_STATUS) ]; then \
-	  res=`cat $(CHECK_STATUS)`; \
-	  if [ "$$res" -eq "0" ]; then \
-	    echo; echo "Complete Test Suite:  FAILED"; \
-	    echo; echo "Review output to identify failure(s)"; \
-	  else \
-	    echo; echo "Complete Test Suite:  PASSED";\
-	  fi; \
-	else \
-	  echo; echo "*******"; \
-	  echo "WARNING:  $(CHECK_STATUS) is missing.  Cannot assess suite."; \
-	  echo "*******"; \
-	fi; \
-	rm -f $(CHECK_STATUS)*; \
-	echo; echo "DONE (checkAll)"; echo
+	@$(MAKE) checkSummary; \
+	echo "DONE (checkAll)"; echo
 
 checkClean:
-	rm -f $(CHECK_STATUS) *.o *.mout $(BINARIES)
+	rm -f *.o *.mout $(BINARIES)
 
 checkContracts: all checkSetup
 	@echo; \
 	for dir in $(INSTR_DIRS); do \
 	  echo; echo "Checking instrumented $$dir sources..."; \
-	  ((cd $(RES_DIR)/$$dir &&  $(MAKE) check) || \
-	     (echo 0 > $(CHECK_STATUS))); \
-	  CSFN=$(CHECK_STATUS)-$$dir; \
+	  CSFN=$(CHECK_ALL_STATUS)-$$dir; \
+	  $(MAKE) -n -C $(RES_DIR)/$$dir checkAll || echo 0 > $$CSFN; \
 	  if [ -f "$$CSFN" ]; then \
 	    res=`cat $$CSFN`; \
 	    if [ "$$res" -eq "0" ]; then \
 	      echo "$$dir test suite failed..."; \
-	      echo 0 > $(CHECK_STATUS); \
+	      echo 0 > $(CHECK_SRC_STATUS); \
 	    else \
 	      echo "$$dir test suite passed..."; \
 	    fi; \
 	  else \
 	    echo "ERROR: Unable to detect $$CSFN"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo 0 > $(CHECK_SRC_STATUS); \
 	  fi; \
 	done
 
 checkSetup: 
-	@if [ ! -f $(CHECK_STATUS) ]; then \
-	  echo 1 > $(CHECK_STATUS); \
+	@if [ ! -f $(CHECK_SRC_STATUS) ]; then \
+	  echo 1 > $(CHECK_SRC_STATUS); \
+	fi
+
+checkSummary:
+	@echo; \
+	if [ -f $(CHECK_SRC_STATUS) ]; then \
+	  res=`cat $(CHECK_SRC_STATUS)`; \
+	  if [ "$$res" -eq "0" ]; then \
+	    echo; echo "Complete Test Suite:  FAILED";\
+	    echo; echo "Review output to identify failure(s)"; \
+	    echo 0 > $(CHECK_ALL_STATUS); \
+	  else \
+	    echo; echo "Complete Test Suite:  PASSED";\
+	  fi; \
+	  rm -f $(CHECK_SRC_STATUS); \
+	else \
+	  echo; echo "***********"; \
+	  echo "WARNING:  Cannot assess test suite."; \
+	  echo "          $(CHECK_SRC_STATUS) is missing."; \
+	  echo "***********"; \
+	  echo 0 > $(CHECK_ALL_STATUS); \
 	fi
 
 $(KC_EXE): $(KC_EXE).c
@@ -169,7 +168,7 @@ $(VCI_EXE): $(VCI_EXE).cpp $(BASE_CLAUSE_SOURCES) $(BASE_CLAUSE_OBJECTS)
 
 
 checkKnapsackDiffs: 
-	@echo "...Comparing runs of $$EXE1 and $$EXE2 with target $$KT..."; \
+	@echo "..Comparing runs of $$EXE1 and $$EXE2 with target $$KT"; \
 	mkdir -p $(BASE_RES_DIR); \
 	if [ "$$EXE1" != "" ]; then \
 	  if [ "$$EXE2" != "" ]; then \
@@ -182,31 +181,31 @@ checkKnapsackDiffs:
 	        DIFFS=$(BASE_RES_DIR)/$$PRE-$$KT.diffs; \
 	        diff $$OFN1 $$OFN2 > $$DIFFS; \
                 if [ -s $$DIFFS ]; then \
-	          echo "......*** $$PRE $$COMP are different ***"; \
-	          echo 0 > $(CHECK_STATUS); \
+	          echo "....*** $$PRE $$COMP are different ***"; \
+	          echo 0 > $(CHECK_SRC_STATUS); \
 	        else \
-	          echo "......$$PRE $$COMP are identical"; \
+	          echo "....$$PRE $$COMP are identical"; \
 	          if [ -f $$DIFFS ]; then \
-	            echo ".........Removing empty differences file"; \
+	            echo ".......Removing empty differences file"; \
 	            rm -f $$DIFFS; \
 	          fi; \
 	        fi; \
 	      else \
-	        echo "......ERROR:  Missing COMP definition"; \
-	        echo 0 > $(CHECK_STATUS); \
+	        echo "....ERROR:  Missing COMP definition"; \
+	        echo 0 > $(CHECK_SRC_STATUS); \
 	      fi; \
 	    else \
-	      echo "......ERROR:  Missing PRE definition"; \
-	      echo 0 > $(CHECK_STATUS); \
+	      echo "....ERROR:  Missing PRE definition"; \
+	      echo 0 > $(CHECK_SRC_STATUS); \
 	    fi; \
 	  else \
-	    echo "......ERROR:  Missing EXE2 definition"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo "....ERROR:  Missing EXE2 definition"; \
+	    echo 0 > $(CHECK_SRC_STATUS); \
 	  fi; \
 	else \
-	  echo "......ERROR:  Missing EXE1 definition"; \
-	  echo 0 > $(CHECK_STATUS); \
-	fi;
+	  echo "....ERROR:  Missing EXE1 definition"; \
+	  echo 0 > $(CHECK_SRC_STATUS); \
+	fi
 
 checkKnapsacks: $(KS_BINARIES)
 	@echo; echo "Running solvers with target=$$KT..."; \
@@ -225,7 +224,7 @@ checkKnapsackTests:
 	$(MAKE) checkKnapsacks KT=0; \
 	$(MAKE) checkKnapsacks KT=10; \
 	$(MAKE) checkKnapsacks KT=; \
-	echo; echo "DONE (checkKnapsackTests)"; echo
+	echo "DONE (checkKnapsackTests)"
 
 checkRose: checkRosePrinters checkRoseTranslators
 
@@ -247,19 +246,18 @@ checkRosePrinter: $(EXE)
 	  n=`expr $$n + 1`; \
 	  BASE=`echo $$file | sed 's/..\/examples\/\([^.]*\).*/\1/g'`; \
 	  EXT=`echo $$file | sed 's/..\/examples\/[^.]*.\(.*\)/\1/g'`; \
-	  echo "...Processing $$BASE.$$EXT"; \
+	  echo "..Processing $$BASE.$$EXT"; \
 	  OFN=$$OUTDIR/$$BASE.mout; \
 	  ./$(EXE) $(ROSE_OPTS) -c $$file > $$OFN; \
 	  if [ -s $$OFN ]; then \
 	    ok=`expr $$ok + 1`; \
-	    echo "......Results in $$OFN"; \
+	    echo "....Results in $$OFN"; \
 	  else \
-	    echo "......FAILED on $$file"; echo; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo "....FAILED on $$file"; echo; \
+	    echo 0 > $(CHECK_SRC_STATUS); \
 	  fi; \
 	done; \
-	echo; \
-	echo "...Successfully processed $$ok of $$n files."; \
+	echo "..Successfully processed $$ok of $$n files."; \
 	echo "DONE (checkRosePrinter)"; echo
 
 checkRoseTranslators: checkRCI checkVCI
@@ -283,7 +281,7 @@ checkRoseTrans: $(EXE)
 	  n=`expr $$n + 1`; \
 	  BASE=`echo $$file | sed 's/..\/examples\/\([^.]*\).*/\1/g'`; \
 	  EXT=`echo $$file | sed 's/..\/examples\/[^.]*.\(.*\)/\1/g'`; \
-	  echo "...Processing $$BASE.$$EXT"; \
+	  echo "..Processing $$BASE.$$EXT"; \
 	  OFN=rose_$$BASE.$$EXT; \
 	  ERRFN=$$OUTDIR/$$BASE.err; \
 	  ./$(EXE) $(ROSE_OPTS) $$file 2> $$ERRFN; \
@@ -299,31 +297,30 @@ checkRoseTrans: $(EXE)
 	    grep PCE_UPDATE_EST_TIME $$OFN | wc -l >> $$ERFN; \
 	    diff $$ERFN $$ORFN > $$ERFN.diffs; \
             if [ -s $$ERFN.diffs ]; then \
-	      echo "......*** $$ERFN $$ORFN are different ***"; \
+	      echo "....*** $$ERFN $$ORFN are different ***"; \
 	      cat $$ERFN.diffs; \
-	      echo "......FAILED on $$file"; echo; \
-	      echo 0 > $(CHECK_STATUS); \
+	      echo "....FAILED on $$file"; echo; \
+	      echo 0 > $(CHECK_SRC_STATUS); \
 	    else \
-	      echo "......$$ERFN $$ORFN are identical"; \
+	      echo "....$$ERFN $$ORFN are identical"; \
 	      ok=`expr $$ok + 1`; \
 	    fi; \
 	    DESTFN=$$OUTDIR/$$BASE.$$EXT; \
 	    mv -f $$OFN $$DESTFN; \
-	    echo "......Unparse results in $$DESTFN"; \
+	    echo "....Unparse results in $$DESTFN"; \
 	  else \
-	    echo "......No output generated.  FAILED on $$file"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo "....No output generated.  FAILED on $$file"; \
+	    echo 0 > $(CHECK_SRC_STATUS); \
 	  fi; \
 	  if [ ! -s $$ERRFN ]; then \
-	    echo "......Removing empty error file."; \
+	    echo "....Removing empty error file."; \
 	    rm -f $$ERRFN; \
 	  fi; \
-	  echo; \
 	done; \
-	echo; echo "...Successfully processed $$ok of $$n files."; echo; \
+	echo; echo "..Successfully processed $$ok of $$n files."; echo; \
         if [ "$$ok" = "$$n" ]; then \
 	  echo "Copying Makefile to $$OUTDIR"; \
-	  cat Makefile.trans | sed 's/FIXME/${SDIR}/g' > $$OUTDIR/Makefile; \
+	  cat Makefile.trans | sed 's/REPLACEME/${SDIR}/g' > $$OUTDIR/Makefile;\
 	  echo "Copying configuration file(s) to $$OUTDIR"; \
 	  cp -f *.config $$OUTDIR; \
 	  echo "Copying header files to $$OUTDIR"; \
@@ -331,9 +328,9 @@ checkRoseTrans: $(EXE)
 	  echo "Try 'make PCEFLAGS=-DPAUL_CONTRACTS check' in $$OUTDIR"; \
 	else \
 	  echo "ERROR: Must resolve issues before able to build translations.";\
-	  echo 0 > $(CHECK_STATUS); \
+	  echo 0 > $(CHECK_SRC_STATUS); \
         fi; \
-	echo "DONE (checkRoseTran)"; echo
+	echo "DONE (checkRoseTran)"
 
 
 clean:
diff --git a/pcontracts/src/examples/Makefile.trans b/pcontracts/src/examples/Makefile.trans
--- a/pcontracts/src/examples/Makefile.trans
+++ b/pcontracts/src/examples/Makefile.trans
@@ -1,14 +1,20 @@
 ROOT_DIR=../..
-EX_DIR=${ROOT_DIR}/src/examples
-RT_DIR=$(ROOT_DIR)/src/runtime
-BASE_ORACLE_DIR=$(ROOT_DIR)/src/data
 
-MAKE= make --no-print-directory
+import $(ROOT_DIR)/make.inc
 
-BASE_TEST_DIR=FIXME
+SRC_DIR=$(ROOT_DIR)/src
+
+EX_DIR=$(SRC_DIR)/examples
+RT_DIR=$(SRC_DIR)/runtime
+BASE_ORACLE_DIR=$(SRC_DIR)/data
+
+MAKE=make --no-print-directory
+
+# NOTE: The following is automatically replaced by the examples Makefile
+BASE_TEST_DIR=REPLACEME
 
 ORACLE_DIR=$(BASE_ORACLE_DIR)/$(BASE_TEST_DIR)
-CHECK_STATUS=$(ROOT_DIR)/.checkStatus-$(BASE_TEST_DIR)
+CHECK_EX_STATUS=$(ROOT_DIR)/$(CHECK_STATUS)-$(BASE_TEST_DIR)
 
 #
 # Be sure to call this with 'make PCEFLAGS=-DPAUL_CONTRACTS' to enable 
@@ -72,25 +78,25 @@ $(UKCPP_EXE): $(UKCPP_EXE).cpp $(UKCPP_EXE).o $(CE_OBJ)
 	$(CXX) -o $(UKCPP_EXE) $(LDFLAGS) $(UKCPP_EXE).o $(CE_OBJ)
 
 check: checkClean checkSetup all checkBasicsCore checkSummary
-	@echo; echo "DONE (check)"; echo
+	@echo "DONE (check)"; echo
 
 checkAll: checkClean checkSetup all checkBasicsCore checkContractsCore \
 	    checkSummary
-	@echo; echo "DONE (checkAll)"; echo
+	@echo "DONE (checkAll)"; echo
 	
 
 checkBasics: checkClean checkSetup all checkBasicsCore checkSummary
-	@echo; echo "DONE (checkBasics)"; echo
+	@echo "DONE (checkBasics)"
 
 checkBasicsCore: checkKC checkKCpp checkKnapsack checkUK
-	@echo; echo "DONE (checkBasicsCore)"; echo
+	@echo "DONE (checkBasicsCore)"
 
 checkContracts:  checkClean checkSetup all checkContractsCore checkSummary
-	@echo; echo "DONE (checkContracts)"; echo
+	@echo "DONE (checkContracts)"
 
 checkContractsCore: 
-	@echo; echo "Checking contracts..."; \
-	$(MAKE) PCEFLAGS=-DPAUL_CONTRACTS || echo 0 > $(CHECK_STATUS); \
+	@echo "Checking contracts..."; \
+	$(MAKE) PCEFLAGS=-DPAUL_CONTRACTS check || echo 0 > $(CHECK_EX_STATUS);\
 	ok=0; \
 	n=0; \
 	for exe in $(BINARIES); do \
@@ -98,29 +104,31 @@ checkContractsCore:
 	  echo "..Processing $$exe"; \
 	  ORFN=$(ORACLE_DIR)/$$exe.mout; \
 	  TFN=$$exe.mout; \
-	  ./$$exe > $$exe.mout; \
+	  ./$$exe > $$TRN; \
 	  if [ -f $$ORFN ]; then \
 	    diff $$TFN $$ORFN > $$TFN.diffs; \
 	    if [ -s $$TFN.diffs ]; then \
-	      echo "....*** $$TFN $$ORFN are different ***"; \
+	      echo "....*** $$TFN and $$ORFN are different ***"; \
 	      cat $$TFN.diffs; \
 	      echo "....FAILED on $$exe"; echo; \
-	      echo 0 > $(CHECK_STATUS); \
+	      echo 0 > $(CHECK_EX_STATUS); \
 	    else \
-	      echo "....$$TFN $$ORFN are identical"; \
+	      echo "....$$TFN and $$ORFN are identical"; \
 	      ok=`expr $$ok + 1`; \
 	    fi; \
+	  else \
+	    echo "....*** $$ORFN is missing ***"; \
+	    echo 0 > $(CHECK_EX_STATUS); \
 	  fi; \
 	done; \
-	echo; \
-	echo; echo "...Successfully processed $$ok of $$n files."; \
+	echo "...Successfully processed $$ok of $$n files."; \
 	@echo; echo "DONE (checkContractsCore)"; echo
 
-# Do NOT remove $(CHECK_STATUS) as long as the root makefile expects it
+# Do NOT remove $(CHECK_EX_STATUS) as long as the root makefile expects it
 checkSummary:
 	@echo; \
-	if [ -f $(CHECK_STATUS) ]; then \
-	  res=`cat $(CHECK_STATUS)`; \
+	if [ -f $(CHECK_EX_STATUS) ]; then \
+	  res=`cat $(CHECK_EX_STATUS)`; \
 	  if [ "$$res" -eq "0" ]; then \
 	    echo "$$BASE_TEST_DIR Test Suite:  FAILED"; \
 	    echo; echo "Review output to identify failure(s)"; \
@@ -129,17 +137,16 @@ checkSummary:
 	  fi; \
 	else \
 	  echo; echo "*******"; \
-	  echo "WARNING:  $(CHECK_STATUS) is missing.  "; \
+	  echo "WARNING:  $(CHECK_EX_STATUS) is missing.  "; \
 	  echo "          Cannot assess $$BASE_TEST_DIR test suite."; \
 	  echo "*******"; \
-	fi; \
-	echo "DONE (checkSummary)"; echo
+	fi
 
 checkClean:
 	@rm -f *.o *.mout $(BINARIES)
 
 checkSetup:
-	@echo 1 > $(CHECK_STATUS)
+	@echo 1 > $(CHECK_EX_STATUS)
 
 checkKC: $(LKC_EXE) $(UKC_EXE)
 	@echo "Checking C knapsack programs..."; \
@@ -152,18 +159,18 @@ checkKC: $(LKC_EXE) $(UKC_EXE)
 	    diff $(LKC_EXE).mout $(UKC_EXE).mout > checkKC.diffs 2>&1; \
 	    if [ -s checkKC.diffs ]; then \
 	      echo "ERROR: Different C knapsack results"; \
-	      echo 0 > $(CHECK_STATUS); \
+	      echo 0 > $(CHECK_EX_STATUS); \
 	    else \
 	      echo "SUCCESS: Identical C knapsack results!"; \
 	    fi; \
 	    rm -f checkKC.diffs; \
 	  else \
 	    echo "ERROR: Cannot find or empty $(UKC_EXE)"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo 0 > $(CHECK_EX_STATUS); \
 	  fi; \
 	else \
 	  echo "ERROR: Cannot find or empty $(LKC_EXE)"; \
-	  echo 0 > $(CHECK_STATUS); \
+	  echo 0 > $(CHECK_EX_STATUS); \
 	fi; \
 	echo "DONE (checkKC)"; echo
 
@@ -184,12 +191,12 @@ checkKCpp: $(LKCPP_EXE) $(UKCPP_EXE)
 	          echo "  known C++ precondition violation (label)."; \
 	        else \
 	          echo "ERROR: Different C++ knapsack results"; \
-	          echo 0 > $(CHECK_STATUS); \
+	          echo 0 > $(CHECK_EX_STATUS); \
 	        fi; \
 	        rm -f checkKCpp-pt.mout; \
 	      else \
 	        echo "ERROR: Different C++ knapsack results"; \
-	        echo 0 > $(CHECK_STATUS); \
+	        echo 0 > $(CHECK_EX_STATUS); \
 	      fi; \
 	    else \
 	      echo "SUCCESS: Identical C++ knapsack results!"; \
@@ -197,11 +204,11 @@ checkKCpp: $(LKCPP_EXE) $(UKCPP_EXE)
 	    rm -f checkKCpp.diffs; \
 	  else \
 	    echo "ERROR: Cannot find or empty $(UKCPP_EXE)"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo 0 > $(CHECK_EX_STATUS); \
 	  fi; \
 	else \
 	  echo "ERROR: Cannot find or empty $(LKCPP_EXE)"; \
-	  echo 0 > $(CHECK_STATUS); \
+	  echo 0 > $(CHECK_EX_STATUS); \
 	fi; \
 	echo "DONE (checkKCpp)"; echo
 
@@ -223,12 +230,12 @@ checkKnapsack: $(LKC_EXE) $(LKCPP_EXE)
 	          echo "  known C++ precondition violation (label)."; \
 	        else \
 	          echo "ERROR: Different C and C++ knapsack results"; \
-	          echo 0 > $(CHECK_STATUS); \
+	          echo 0 > $(CHECK_EX_STATUS); \
 	        fi; \
 	        rm -f checkKnapsack-pt.mout; \
 	      else \
 	        echo "ERROR: Different C and C++ knapsack results"; \
-	        echo 0 > $(CHECK_STATUS); \
+	        echo 0 > $(CHECK_EX_STATUS); \
 	      fi; \
 	    else \
 	      echo "SUCCESS: Identical C and C++ knapsack results!"; \
@@ -236,11 +243,11 @@ checkKnapsack: $(LKC_EXE) $(LKCPP_EXE)
 	    rm -f checkKnapsack.diffs; \
 	  else \
 	    echo "ERROR: Cannot find or empty $(LKC_EXE)"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo 0 > $(CHECK_EX_STATUS); \
 	  fi; \
 	else \
 	  echo "ERROR: Cannot find or empty $(LKCPP_EXE)"; \
-	  echo 0 > $(CHECK_STATUS); \
+	  echo 0 > $(CHECK_EX_STATUS); \
 	fi; \
 	echo "DONE (checkKnapsack)"; echo
 
@@ -261,12 +268,12 @@ checkUK: $(UKC_EXE) $(LKCPP_EXE)
 	          echo "  results due to known C++ precondition violation."; \
 	        else \
 	          echo "ERROR: Different C and C++ unlabeled knapsack results";\
-	          echo 0 > $(CHECK_STATUS); \
+	          echo 0 > $(CHECK_EX_STATUS); \
 	        fi; \
 	        rm -f checkUK-pt.mout; \
 	      else \
 	        echo "ERROR: Different C and C++ unlabeled knapsack results"; \
-	        echo 0 > $(CHECK_STATUS); \
+	        echo 0 > $(CHECK_EX_STATUS); \
 	      fi; \
 	    else \
 	      echo "SUCCESS: Identical C and C++ unlabeled knapsack results!"; \
@@ -274,16 +281,18 @@ checkUK: $(UKC_EXE) $(LKCPP_EXE)
 	    rm -f checkUK.diffs; \
 	  else \
 	    echo "ERROR: Cannot find or empty $(UKC_EXE)"; \
-	    echo 0 > $(CHECK_STATUS); \
+	    echo 0 > $(CHECK_EX_STATUS); \
 	  fi; \
 	else \
 	  echo "ERROR: Cannot find or empty Unlabeledknapsack"; \
-	  echo 0 > $(CHECK_STATUS); \
+	  echo 0 > $(CHECK_EX_STATUS); \
 	fi; \
 	echo "DONE (checkUK)"; echo
 
 clean:
 	rm -f *.o *.mout *.out *.diffs *.stats *.trace 
+
+clean-all: cleanAll
 
 cleanAll: clean cleanExe
 
