braid now has a man page, too

diff --git a/braid/Makefile.in b/braid/Makefile.in
--- a/braid/Makefile.in
+++ b/braid/Makefile.in
@@ -42,9 +42,10 @@ build_triplet = @build@
 host_triplet = @host@
 target_triplet = @target@
 DIST_COMMON = README $(am__configure_deps) $(am__python_PYTHON_DIST) \
-	$(nobase_include_HEADERS) $(nobase_python_PYTHON) \
-	$(noinst_PYTHON) $(srcdir)/Doxyfile.in $(srcdir)/Makefile.am \
-	$(srcdir)/Makefile.in $(srcdir)/braid/Makefile.include \
+	$(dist_man_MANS) $(nobase_include_HEADERS) \
+	$(nobase_python_PYTHON) $(noinst_PYTHON) $(srcdir)/Doxyfile.in \
+	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
+	$(srcdir)/braid/Makefile.include \
 	$(srcdir)/chapel-patches/Makefile.include \
 	$(srcdir)/patch-chapel-compiler.sh.in \
 	$(srcdir)/regression/interop/Makefile.include \
@@ -138,7 +139,8 @@ am__base_list = \
   sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
 am__installdirs = "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(bindir)" \
 	"$(DESTDIR)$(infodir)" "$(DESTDIR)$(pythondir)" \
-	"$(DESTDIR)$(pythondir)" "$(DESTDIR)$(includedir)"
+	"$(DESTDIR)$(pythondir)" "$(DESTDIR)$(man1dir)" \
+	"$(DESTDIR)$(includedir)"
 LTLIBRARIES = $(nobase_pyexec_LTLIBRARIES)
 braid_scanner_la_DEPENDENCIES =
 am_braid_scanner_la_OBJECTS = braid_scanner_la-scanner.lo
@@ -225,6 +227,9 @@ DVIPS = dvips
 am__python_PYTHON_DIST = $(top_srcdir)/contrib/ply/yacc.py \
 	contrib/argparse-1.1/argparse.py
 py_compile = $(top_srcdir)/config/py-compile
+man1dir = $(mandir)/man1
+NROFF = nroff
+MANS = $(dist_man_MANS)
 HEADERS = $(nobase_include_HEADERS)
 ETAGS = etags
 CTAGS = ctags
@@ -619,11 +624,10 @@ BABEL_TESTS = \
   regression/interop/inherit/runChapel/inherittest.chpl \
   regression/interop/args/runChapel/argstest.chpl \
   regression/interop/arrays/runChapel/arraystest.chpl \
-  regression/interop/strings/runChapel/stringstest.chpl \
-  regression/interop/exceptions/runChapel/exceptionstest.chpl
+  regression/interop/strings/runChapel/stringstest.chpl 
 
 BABEL_TESTNAMES = \
-  args arrays inherit strings exceptions
+  args arrays inherit strings
 
 @ENABLE_INTEROP_REGRESSION_TRUE@CHPL_LOG_COMPILER = sh 
 # FIXME:
@@ -673,6 +677,7 @@ DISTCHECK_CONFIGURE_FLAGS = --disable-documentation \
   PKG_CONFIG_PATH=$(prefix)/lib/pkgconfig:$(PKG_CONFIG_PATH)
 
 info_TEXINFOS = doc/braid.texi
+dist_man_MANS = $(srcdir)/doc/braid.1
 noinst_SCRIPTS = patch-chapel-compiler.sh.in
 all: $(BUILT_SOURCES)
 	$(MAKE) $(AM_MAKEFLAGS) all-am
@@ -1097,6 +1102,44 @@ uninstall-pythonPYTHON:
 	cd "$(DESTDIR)$(pythondir)" && rm -f $$filesc || exit $$?; \
 	echo " ( cd '$(DESTDIR)$(pythondir)' && rm -f" $$fileso ")"; \
 	cd "$(DESTDIR)$(pythondir)" && rm -f $$fileso
+install-man1: $(dist_man_MANS)
+	@$(NORMAL_INSTALL)
+	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
+	@list=''; test -n "$(man1dir)" || exit 0; \
+	{ for i in $$list; do echo "$$i"; done; \
+	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
+	  sed -n '/\.1[a-z]*$$/p'; \
+	} | while read p; do \
+	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	  echo "$$d$$p"; echo "$$p"; \
+	done | \
+	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
+	sed 'N;N;s,\n, ,g' | { \
+	list=; while read file base inst; do \
+	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
+	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
+	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
+	  fi; \
+	done; \
+	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
+	while read files; do \
+	  test -z "$$files" || { \
+	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
+	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
+	done; }
+
+uninstall-man1:
+	@$(NORMAL_UNINSTALL)
+	@list=''; test -n "$(man1dir)" || exit 0; \
+	files=`{ for i in $$list; do echo "$$i"; done; \
+	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
+	  sed -n '/\.1[a-z]*$$/p'; \
+	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
+	test -z "$$files" || { \
+	  echo " ( cd '$(DESTDIR)$(man1dir)' && rm -f" $$files ")"; \
+	  cd "$(DESTDIR)$(man1dir)" && rm -f $$files; }
 install-nobase_includeHEADERS: $(nobase_include_HEADERS)
 	@$(NORMAL_INSTALL)
 	test -z "$(includedir)" || $(MKDIR_P) "$(DESTDIR)$(includedir)"
@@ -1335,6 +1378,19 @@ recheck recheck-html:
 @am__EXEEXT_TRUE@	@p='$<'; $(am__check_pre) $(CHPL_LOG_COMPILE) "$$tst" $(am__check_post)
 
 distdir: $(DISTFILES)
+	@list='$(MANS)'; if test -n "$$list"; then \
+	  list=`for p in $$list; do \
+	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
+	  if test -n "$$list" && \
+	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
+	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
+	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
+	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
+	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
+	    exit 1; \
+	  else :; fi; \
+	else :; fi
 	$(am__remove_distdir)
 	test -d "$(distdir)" || mkdir "$(distdir)"
 	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
@@ -1494,9 +1550,10 @@ check-am: all-am
 	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: $(BUILT_SOURCES)
 	$(MAKE) $(AM_MAKEFLAGS) check-am
-all-am: Makefile $(INFO_DEPS) $(LTLIBRARIES) $(SCRIPTS) $(HEADERS)
+all-am: Makefile $(INFO_DEPS) $(LTLIBRARIES) $(SCRIPTS) $(MANS) \
+		$(HEADERS)
 installdirs:
-	for dir in "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(infodir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(includedir)"; do \
+	for dir in "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(infodir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(includedir)"; do \
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: $(BUILT_SOURCES)
@@ -1562,10 +1619,10 @@ info: info-am
 
 info-am: $(INFO_DEPS)
 
-install-data-am: install-info-am install-nobase_includeHEADERS \
-	install-nobase_pythonPYTHON install-pythonPYTHON
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
+install-data-am: install-info-am install-man \
+	install-nobase_includeHEADERS install-nobase_pythonPYTHON \
+	install-pythonPYTHON
+
 install-dvi: install-dvi-am
 
 install-dvi-am: $(DVIS)
@@ -1638,7 +1695,7 @@ install-info-am: $(INFO_DEPS)
 	    install-info --info-dir="$(DESTDIR)$(infodir)" "$(DESTDIR)$(infodir)/$$relfile" || :;\
 	  done; \
 	else : ; fi
-install-man:
+install-man: install-man1
 
 install-pdf: install-pdf-am
 
@@ -1690,15 +1747,16 @@ ps: ps-am
 ps-am: $(PSS)
 
 uninstall-am: uninstall-binSCRIPTS uninstall-dvi-am uninstall-html-am \
-	uninstall-info-am uninstall-nobase_includeHEADERS \
+	uninstall-info-am uninstall-man \
+	uninstall-nobase_includeHEADERS \
 	uninstall-nobase_pyexecLTLIBRARIES \
 	uninstall-nobase_pythonPYTHON uninstall-pdf-am uninstall-ps-am \
 	uninstall-pythonPYTHON
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
-.MAKE: all check check-am check-html install install-am \
-	install-data-am install-strip recheck recheck-html \
-	uninstall-am
+
+uninstall-man: uninstall-man1
+
+.MAKE: all check check-am check-html install install-am install-strip \
+	recheck recheck-html
 
 .PHONY: CTAGS GTAGS all all-am am--refresh check check-TESTS check-am \
 	check-html clean clean-aminfo clean-cscope clean-generic \
@@ -1709,10 +1767,10 @@ uninstall-am: uninstall-binSCRIPTS uninstall-dvi-am uninstall-html-am \
 	distclean-generic distclean-libtool distclean-local \
 	distclean-tags distcleancheck distdir distuninstallcheck dvi \
 	dvi-am html html-am info info-am install install-am \
-	install-binSCRIPTS install-data install-data-am \
-	install-data-hook install-dvi install-dvi-am install-exec \
-	install-exec-am install-html install-html-am install-info \
-	install-info-am install-man install-nobase_includeHEADERS \
+	install-binSCRIPTS install-data install-data-am install-dvi \
+	install-dvi-am install-exec install-exec-am install-html \
+	install-html-am install-info install-info-am install-man \
+	install-man1 install-nobase_includeHEADERS \
 	install-nobase_pyexecLTLIBRARIES install-nobase_pythonPYTHON \
 	install-pdf install-pdf-am install-ps install-ps-am \
 	install-pythonPYTHON install-strip installcheck \
@@ -1722,8 +1780,8 @@ uninstall-am: uninstall-binSCRIPTS uninstall-dvi-am uninstall-html-am \
 	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
 	pdf pdf-am ps ps-am recheck recheck-html tags uninstall \
 	uninstall-am uninstall-binSCRIPTS uninstall-dvi-am \
-	uninstall-hook uninstall-html-am uninstall-info-am \
-	uninstall-nobase_includeHEADERS \
+	uninstall-html-am uninstall-info-am uninstall-man \
+	uninstall-man1 uninstall-nobase_includeHEADERS \
 	uninstall-nobase_pyexecLTLIBRARIES \
 	uninstall-nobase_pythonPYTHON uninstall-pdf-am uninstall-ps-am \
 	uninstall-pythonPYTHON
@@ -1819,13 +1877,26 @@ doc:
 
 doc/html/index.html:
 	$(MAKE) doc
-# Convert the info file into a man page
-install-data-hook:
-	mkdir -p $(DESTDIR)$(mandir)/man1
-	info2man $(DESTDIR)$(infodir)/braid.info >$(DESTDIR)$(mandir)/man1/braid.1
 
-uninstall-hook:
-	rm -f $(DESTDIR)$(mandir)/man1/braid.1
+# We are distributing the compiled manpage so we don't depend on rst2man
+# Insert the output of braid --help into the MAN page.
+$(srcdir)/doc/braid.1: doc/man_header.txt $(top_builddir)/braid/braid COPYRIGHT
+	$(AM_V_GEN)
+	@cat $< |sed -e 's/@DATE@/$(shell date +%Y-%m-%d)/g' \
+                     -e 's/\@VERSION\@/$(PACKAGE_VERSION)/g' >braid.txt
+	@sh $(top_builddir)/braid/braid --help \
+	|  sed -e 's/usage:/\nSYNOPSIS\n========\n\n/' \
+               -e 's/:$$/\n~~~~~~~~~~~~~~~~~~~~\n\n/' \
+               -e 's/^Braid/\nDESCRIPTION\n===========\n\nBraid/' \
+               -e 's/pos/OPTIONS\n=======\n\npos/' >>braid.txt
+	@echo >>braid.txt
+	@cat $(srcdir)/COPYRIGHT >>braid.txt
+	@if [ -n `which rst2man` ]; then \
+		rst2man -v braid.txt $@; \
+	else \
+		echo "**WARNING rst2man not installed, did not update $@"; \
+	fi
+	@ echo rm -f braid.txt
 
 distclean-local:
 	rm -f toolcheck.log
